sudo: false
language: rust
before_script:
  - curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git cobalt-org/cobalt.rs --crate cobalt
  - export PATH="$PATH:/home/travis/.cargo/bin"
#- cargo install cobalt-bin --features="syntax-highlight"
#- export PATH="$PATH:/home/travis/.cargo/bin"
script:
  - cobalt build
deploy:
  provider: pages
  repo: mattyhall/mattyhall.github.io
  target_branch: master
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
