sudo: false
language: rust
before_script:
- cargo install cobalt-bin
- export PATH="$PATH:/home/travis/.cargo/bin"
script:
- cobalt build
deploy:
  provider: pages
  repo: mattyhall.github.io
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
